import sharp from "sharp"

/**
 * Extracts the EXIF Orientation tag (0x0112) from TIFF/CR2/NEF/ARW headers in IFD0.
 * Returns 1 (normal), 3 (180°), 6 (90° CW), 8 (270° CW), or null if not found.
 */
export function extractRawOrientation(buffer: Buffer): number | null {
  if (buffer.length < 16) return null

  const isLittleEndian = buffer[0] === 0x49 && buffer[1] === 0x49 // "II"
  const isBigEndian = buffer[0] === 0x4d && buffer[1] === 0x4d // "MM"

  if (!isLittleEndian && !isBigEndian) return null

  const readU16 = (pos: number) => (isLittleEndian ? buffer.readUInt16LE(pos) : buffer.readUInt16BE(pos))
  const readU32 = (pos: number) => (isLittleEndian ? buffer.readUInt32LE(pos) : buffer.readUInt32BE(pos))

  const magic = readU16(2)
  if (magic !== 42 && magic !== 0x4352 && magic !== 0x55) return null

  const ifd0Offset = readU32(4)
  if (ifd0Offset < 8 || ifd0Offset + 2 > buffer.length) return null

  const numEntries = readU16(ifd0Offset)
  let pos = ifd0Offset + 2

  for (let i = 0; i < numEntries; i++) {
    if (pos + 12 > buffer.length) break
    const tag = readU16(pos)
    if (tag === 0x0112) {
      // Tag 0x0112 is Orientation
      return readU16(pos + 8)
    }
    pos += 12
  }

  return null
}

/**
 * Extracts a complete JPEG buffer starting at `startIndex` by parsing standard JPEG marker segments.
 */
function findCompleteJpeg(buffer: Buffer, startIndex: number): Buffer | null {
  if (startIndex + 4 > buffer.length) return null
  if (buffer[startIndex] !== 0xff || buffer[startIndex + 1] !== 0xd8) return null

  let pos = startIndex + 2
  const len = buffer.length

  while (pos < len - 1) {
    if (buffer[pos] !== 0xff) {
      pos++
      continue
    }

    // Skip fill bytes (0xFF 0xFF...)
    while (pos < len && buffer[pos] === 0xff) {
      pos++
    }
    if (pos >= len) break

    const marker = buffer[pos]
    pos++

    // EOI (End of Image)
    if (marker === 0xd9) {
      return buffer.subarray(startIndex, pos)
    }

    // SOS (Start of Scan - image entropy data begins)
    if (marker === 0xda) {
      if (pos + 2 > len) break
      const sosLen = (buffer[pos] << 8) | buffer[pos + 1]
      pos += sosLen

      // Scan entropy stream for real EOI (0xFF 0xD9)
      while (pos < len - 1) {
        if (buffer[pos] === 0xff) {
          const nextByte = buffer[pos + 1]
          if (nextByte === 0xd9) {
            // Found real EOI!
            return buffer.subarray(startIndex, pos + 2)
          }
          // If another non-rst marker, break out of scan
          if (nextByte !== 0x00 && !(nextByte >= 0xd0 && nextByte <= 0xd7) && nextByte !== 0xff) {
            pos += 2
            break
          }
        }
        pos++
      }
      continue
    }

    // Skip non-marker single-byte markers
    if (marker === 0x01 || (marker >= 0xd0 && marker <= 0xd7)) {
      continue
    }

    // For all other markers (APP0..APP15, DQT, SOF0..SOF15, DHT, etc.), read length field
    if (pos + 2 > len) break
    const segmentLength = (buffer[pos] << 8) | buffer[pos + 1]
    if (segmentLength < 2) {
      pos++
      continue
    }
    pos += segmentLength
  }

  return null
}

/**
 * Extracts all embedded JPEG buffers from a camera RAW file (Canon CR2/CR3, Nikon NEF, Sony ARW, Adobe DNG, etc.)
 */
export function extractJpegsFromRaw(buffer: Buffer): Buffer[] {
  const jpegs: Buffer[] = []
  let offset = 0

  while (offset < buffer.length - 4) {
    // Search for JPEG SOI: 0xFF 0xD8 0xFF
    if (buffer[offset] === 0xff && buffer[offset + 1] === 0xd8 && buffer[offset + 2] === 0xff) {
      // 1. Try standard JPEG marker parsing
      const parsed = findCompleteJpeg(buffer, offset)
      if (parsed && parsed.length > 2048) {
        jpegs.push(parsed)
        offset += parsed.length
        continue
      }

      // 2. Fallback: slice from SOI to next SOI or end of buffer
      let nextSoi = -1
      for (let j = offset + 10; j < buffer.length - 4; j++) {
        if (buffer[j] === 0xff && buffer[j + 1] === 0xd8 && buffer[j + 2] === 0xff) {
          nextSoi = j
          break
        }
      }

      const end = nextSoi !== -1 ? nextSoi : buffer.length
      if (end - offset > 2048) {
        jpegs.push(buffer.subarray(offset, end))
      }

      offset = end
    } else {
      offset++
    }
  }

  return jpegs
}

/**
 * Converts a raw or standard image buffer into a Sharp-readable image buffer.
 * For Canon CR2, Nikon NEF, Sony ARW, Adobe DNG, etc., extracts the largest embedded high-res JPEG preview.
 */
export async function getDecodableImageBuffer(buffer: Buffer, filename?: string): Promise<Buffer> {
  const ext = filename?.split(".").pop()?.toLowerCase() ?? ""
  const isRawExt = ["cr2", "cr3", "nef", "arw", "dng", "raf", "orf", "rw2", "pef", "srw", "raw"].includes(ext)

  // If RAW file, DO NOT let libtiff try to decompress the proprietary raw sensor stream directly.
  // Instead, extract the embedded full-resolution/high-res JPEG preview generated by the camera!
  if (isRawExt) {
    const embeddedJpegs = extractJpegsFromRaw(buffer)
    if (embeddedJpegs.length > 0) {
      // Sort by largest byte size (the largest is the full-res preview)
      embeddedJpegs.sort((a, b) => b.length - a.length)

      for (const jpegBuf of embeddedJpegs) {
        try {
          const meta = await sharp(jpegBuf).metadata()
          if (meta && meta.width && meta.height) {
            return jpegBuf
          }
        } catch {
          // If this chunk failed Sharp decode, try next largest candidate
          continue
        }
      }
    }
  }

  // For standard formats (JPG, PNG, WebP, TIFF), decode with Sharp
  try {
    const meta = await sharp(buffer).metadata()
    if (meta && meta.width && meta.height) {
      return buffer
    }
  } catch {
    // If standard decode failed, attempt emergency RAW embedded JPEG extraction
    const embeddedJpegs = extractJpegsFromRaw(buffer)
    if (embeddedJpegs.length > 0) {
      embeddedJpegs.sort((a, b) => b.length - a.length)
      for (const jpegBuf of embeddedJpegs) {
        try {
          const meta = await sharp(jpegBuf).metadata()
          if (meta && meta.width && meta.height) {
            return jpegBuf
          }
        } catch {
          continue
        }
      }
    }
  }

  return buffer
}
